language: ruby
rvm:
  - 2.0.0
gemfile: data/Gemfile
script: sh -c 'cd data && && bundle exec rake db:migrate && bundle exec rake'
deploy:
  provider: heroku
  api_key:
    secure: WYUhMSIxYEUK5BJSZ+8iO2ovi2KiE2Uqcqmiu1R8+RUlInxoDbPrMsKje34Zq+v5/rhPlf8qsr4QJwM22dvqfJcFj9+FAroPtFdnL8aQiO0t7frNdOPJY8wbHM8rlX1RlJRh0XHOr3MNP9vNznzIZ1GogNZNImlzu2EZ8p4DpGc=
  app: bfh-os2-toolchain
  on:
    repo: MatthiasWinzeler/bfh-os2-toolchain
  run: rake db:migrate
